image: node:latest

variables:
  DEPLOY_FOLDER: "/home/alan/prototype"

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh root@$DEPLOY_SERVER "rm -rf $DEPLOY_FOLDER/*"
    - scp -r ./* root@$DEPLOY_SERVER:$DEPLOY_FOLDER
    - ssh root@$DEPLOY_SERVER "cd $DEPLOY_FOLDER && npm install --no-progress && npm run build"
  only:
    - master
